<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>GainMapStego</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x86;x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<PublishProfile>win-$(Platform).pubxml</PublishProfile>
		<UseWinUI>true</UseWinUI>
		<EnableMsixTooling>true</EnableMsixTooling>
		<Nullable>enable</Nullable>
		<Version>0.2.0</Version>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<ApplicationIcon>favicon.ico</ApplicationIcon>
		<WindowsPackageType>None</WindowsPackageType>
		<CETCompat>false</CETCompat>
		<PublishAot>true</PublishAot>
		<OptimizationPreference>Size</OptimizationPreference>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.Segmented" Version="8.2.250402" />
		<PackageReference Include="ComputeSharp.D2D1.WinUI" Version="3.2.0" />
		<PackageReference Include="Microsoft.Graphics.Win2D" Version="1.4.0" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
	</ItemGroup>

	<ItemGroup>
		<None Update="uhdr.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="sample.jpg">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<Content Include="intro.jpg">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<EmbeddedResource Include="favicon.ico" />
	</ItemGroup>

</Project>